"""Algorithm registry.

Single source of truth that maps algorithm ids to their modules,
operations and UI field descriptors. Routes and the frontend are built
generically from this registry so new algorithms can be added without
touching HTTP code.
"""

from __future__ import annotations

from typing import Callable, Dict, List

from app.algorithms import (
    aes,
    aes_gcm,
    argon2_alg,
    bcrypt_alg,
    blake2,
    blake3,
    blowfish,
    caesar,
    chacha20,
    chacha20_poly1305,
    columnar,
    des,
    diffie_hellman,
    ecdh,
    ecdsa_alg,
    ed25519_alg,
    elgamal,
    hkdf,
    hmac_alg,
    hill,
    md5,
    monoalphabetic,
    pbkdf2,
    playfair,
    rail_fence,
    rsa,
    scrypt_alg,
    sha1,
    sha256,
    sha3,
    sha512,
    triple_des,
    twofish,
    vigenere,
    x25519,
)

CATEGORY_LABELS = {
    "classical": "Classical / Historical",
    "symmetric": "Symmetric Encryption",
    "asymmetric": "Asymmetric Encryption",
    "key_exchange": "Key Exchange",
    "hashing": "Hash Function",
    "mac": "Message Authentication (MAC)",
    "kdf": "Password Hashing / Key Derivation",
    "aead": "Authenticated Encryption (AEAD)",
    "signature": "Digital Signatures",
}


def _fields(specs: List[dict]) -> List[dict]:
    return specs


ALGORITHMS: Dict[str, dict] = {
    "caesar": {
        "module": caesar,
        "name": "Caesar Cipher",
        "category": "classical",
        "operations": ["encrypt", "decrypt", "brute_force"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "HELLO WORLD", "required": True},
            {"name": "shift", "type": "number", "label": "Shift (k)",
             "default": 3, "required": True, "min": 1, "max": 25},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "shift (integer 1–25)",
        "block_size": "1 character",
        "description": "Each letter is shifted a fixed number of positions.",
        "formula": "C = (P + k) mod 26",
    },
    "monoalphabetic": {
        "module": monoalphabetic,
        "name": "Monoalphabetic Substitution",
        "category": "classical",
        "operations": ["encrypt", "decrypt", "generate_alphabet"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "HELLO", "required": True},
            {"name": "substitution", "type": "text", "label": "Substitution alphabet",
             "placeholder": "QAZWSXEDCRFVTGBYHNUJMIKOLP", "required": True,
             "default": "QAZWSXEDCRFVTGBYHNUJMIKOLP"},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "substitution alphabet (26 letters)",
        "block_size": "1 character",
        "description": "Each letter maps to a fixed substitute letter.",
        "formula": "cipher(c) = substitution[position(c)]",
    },
    "vigenere": {
        "module": vigenere,
        "name": "Vigenère Cipher",
        "category": "classical",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "ATTACKATDAWN", "required": True},
            {"name": "key", "type": "text", "label": "Keyword",
             "placeholder": "LEMON", "required": True, "default": "LEMON"},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "keyword (letters)",
        "block_size": "1 character",
        "description": "Polyalphabetic shifts selected by a repeating keyword.",
        "formula": "Cᵢ = (Pᵢ + Kᵢ) mod 26",
    },
    "playfair": {
        "module": playfair,
        "name": "Playfair Cipher",
        "category": "classical",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "HELLO WORLD", "required": True},
            {"name": "keyword", "type": "text", "label": "Keyword",
             "placeholder": "MONARCHY", "required": True, "default": "MONARCHY"},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "keyword (letters)",
        "block_size": "2 characters (digraph)",
        "description": "Digraph substitution using a 5×5 key square.",
        "formula": "digraph rules (row/column/rectangle)",
    },
    "hill": {
        "module": hill,
        "name": "Hill Cipher",
        "category": "classical",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "HELP", "required": True},
            {"name": "matrix", "type": "matrix", "label": "Key matrix (2×2 or 3×3)",
             "required": True, "default": [[3, 3], [2, 5]]},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "invertible matrix (mod 26)",
        "block_size": "n letters (2 or 3)",
        "description": "Linear-algebra block cipher over Z/26Z.",
        "formula": "C = K·P (mod 26)",
    },
    "rail_fence": {
        "module": rail_fence,
        "name": "Rail Fence Cipher",
        "category": "classical",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "HELLOWORLD", "required": True},
            {"name": "rails", "type": "number", "label": "Number of rails",
             "default": 3, "required": True, "min": 2, "max": 26},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "number of rails",
        "block_size": "whole message",
        "description": "Zig-zag transposition across n rails.",
        "formula": "zig-zag write, row-by-row read",
    },
    "columnar": {
        "module": columnar,
        "name": "Columnar Transposition",
        "category": "classical",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "text", "type": "textarea", "label": "Plaintext / Ciphertext",
             "placeholder": "HELLOWORLD", "required": True},
            {"name": "key", "type": "text", "label": "Keyword",
             "placeholder": "ZEBRA", "required": True, "default": "ZEBRA"},
        ]),
        "result_type": "text",
        "security_status": "historic",
        "reversible": True,
        "key_kind": "keyword (letters)",
        "block_size": "whole message",
        "description": "Write in rows, read columns in key order.",
        "formula": "column order = alphabetical key order",
    },
    "des": {
        "module": des,
        "name": "DES",
        "category": "symmetric",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "block", "type": "text", "label": "Block (16 hex digits)",
             "placeholder": "0123456789ABCDEF", "required": True,
             "default": "0123456789ABCDEF"},
            {"name": "key", "type": "text", "label": "Key (16 hex digits)",
             "placeholder": "133457799BBCDFF1", "required": True,
             "default": "133457799BBCDFF1"},
        ]),
        "result_type": "text",
        "security_status": "deprecated",
        "reversible": True,
        "key_kind": "56-bit effective key (8 bytes hex)",
        "block_size": "64 bits",
        "description": "64-bit Feistel block cipher with 56-bit key, 16 rounds.",
        "formula": "Feistel network with S-boxes",
    },
    "triple_des": {
        "module": triple_des,
        "name": "3DES (Triple DES)",
        "category": "symmetric",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "block", "type": "text", "label": "Block (16 hex digits)",
             "placeholder": "0123456789ABCDEF", "required": True,
             "default": "0123456789ABCDEF"},
            {"name": "key", "type": "text", "label": "Key (48 hex digits = 3×8 bytes)",
             "placeholder": "133457799BBCDFF1133457799BBCDFF1133457799BBCDFF1",
             "required": True,
             "default": "133457799BBCDFF1133457799BBCDFF1133457799BBCDFF1"},
        ]),
        "result_type": "text",
        "security_status": "deprecated",
        "reversible": True,
        "key_kind": "3 × DES keys (24 bytes hex)",
        "block_size": "64 bits",
        "description": "DES applied three times (EDE) — deprecated, prefer AES.",
        "formula": "C = E(K3, D(K2, E(K1, P)))",
    },
    "aes": {
        "module": aes,
        "name": "AES",
        "category": "symmetric",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "block", "type": "text", "label": "Block (32 hex digits)",
             "placeholder": "00112233445566778899AABBCCDDEEFF", "required": True,
             "default": "00112233445566778899AABBCCDDEEFF"},
            {"name": "key", "type": "text", "label": "Key (32/48/64 hex digits)",
             "placeholder": "000102030405060708090A0B0C0D0E0F", "required": True,
             "default": "000102030405060708090A0B0C0D0E0F"},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": True,
        "key_kind": "128 / 192 / 256 bits (hex)",
        "block_size": "128 bits",
        "description": "Rijndael — the current recommended symmetric cipher.",
        "formula": "SubBytes, ShiftRows, MixColumns, AddRoundKey",
    },
    "blowfish": {
        "module": blowfish,
        "name": "Blowfish",
        "category": "symmetric",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "block", "type": "text", "label": "Block (16 hex digits)",
             "placeholder": "0123456789ABCDEF", "required": True,
             "default": "0123456789ABCDEF"},
            {"name": "key", "type": "text", "label": "Key (8–112 hex digits)",
             "placeholder": "0123456789ABCDEFFEDCBA9876543210", "required": True,
             "default": "0123456789ABCDEFFEDCBA9876543210"},
        ]),
        "result_type": "text",
        "security_status": "deprecated",
        "reversible": True,
        "key_kind": "variable 32–448 bits (4–56 bytes hex)",
        "block_size": "64 bits",
        "description": "Variable-length-key Feistel block cipher by Bruce "
                       "Schneier (1993); deprecated — its 64-bit block is too "
                       "small for modern modes.",
        "formula": "16-round Feistel; F(x) = ((S0[a]+S1[b]) XOR S2[c]) + S3[d]",
    },
    "twofish": {
        "module": twofish,
        "name": "Twofish",
        "category": "symmetric",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "block", "type": "text", "label": "Block (32 hex digits)",
             "placeholder": "00000000000000000000000000000000", "required": True,
             "default": "00000000000000000000000000000000"},
            {"name": "key", "type": "text", "label": "Key (32/48/64 hex digits)",
             "placeholder": "0123456789ABCDEFFEDCBA98765432100011223344556677",
             "required": True,
             "default": "0123456789ABCDEFFEDCBA9876543210"},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": True,
        "key_kind": "128 / 192 / 256 bits (hex)",
        "block_size": "128 bits",
        "description": "AES competition finalist (Schneier et al., 1998): "
                       "128-bit block, 16 rounds, key-dependent S-boxes and "
                       "an MDS matrix over GF(2^8). Unpatented and unbroken.",
        "formula": "g() (keyed S-boxes + MDS) → PHT → 1-bit rotations",
    },
    "chacha20": {
        "module": chacha20,
        "name": "ChaCha20",
        "category": "symmetric",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "message", "type": "textarea",
             "label": "Plaintext / Ciphertext (hex)",
             "placeholder": "Plaintext, or the hex ciphertext when decrypting",
             "required": True},
            {"name": "key", "type": "text", "label": "Key (64 hex digits)",
             "placeholder": "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F",
             "required": True,
             "default": "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F"},
            {"name": "nonce", "type": "text", "label": "Nonce (24 hex digits)",
             "placeholder": "000000000000004A00000000", "required": True,
             "default": "000000000000004A00000000"},
            {"name": "counter", "type": "number", "label": "Initial block counter",
             "default": 1, "required": True, "min": 0},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": True,
        "key_kind": "256-bit key (64 hex) + 96-bit nonce (24 hex)",
        "block_size": "stream cipher (64-byte blocks)",
        "description": "RFC 8439 stream cipher used by TLS 1.3: a keystream "
                       "is XORed with the data — the same operation encrypts "
                       "and decrypts. Requires a unique nonce per key.",
        "formula": "keystream = ChaCha20(key, nonce, counter); C = P XOR keystream",
    },
    "aes_gcm": {
        "module": aes_gcm,
        "name": "AES-GCM",
        "category": "aead",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "plaintext", "type": "textarea", "label": "Plaintext",
             "placeholder": "Hello, world!", "required": True},
            {"name": "ciphertext_hex", "type": "textarea",
             "label": "Ciphertext (hex, ciphertext+tag)",
             "placeholder": "hex ciphertext (incl. 16-byte tag)",
             "required": False},
            {"name": "key_hex", "type": "text", "label": "Key (32/48/64 hex digits)",
             "placeholder": "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F",
             "required": True},
            {"name": "nonce_hex", "type": "text", "label": "Nonce (24 hex digits)",
             "placeholder": "000000000000000000000000", "required": True},
            {"name": "aad", "type": "textarea", "label": "AAD (optional, authenticated)",
             "placeholder": "optional authenticated data", "default": "",
             "required": False},
        ]),
        "result_type": "object",
        "security_status": "secure",
        "reversible": True,
        "key_kind": "128/192/256-bit key (hex) + 96-bit nonce",
        "block_size": "128-bit blocks (CTR + GCTR)",
        "description": "Authenticated encryption: AES in counter mode combined "
                       "with a GHASH tag. Detects any tampering on decryption.",
        "formula": "C = CTR-mode AES; τ = GHASH(H, A, C)",
    },
    "chacha20_poly1305": {
        "module": chacha20_poly1305,
        "name": "ChaCha20-Poly1305",
        "category": "aead",
        "operations": ["encrypt", "decrypt"],
        "fields": _fields([
            {"name": "plaintext", "type": "textarea", "label": "Plaintext",
             "placeholder": "Hello, world!", "required": True},
            {"name": "ciphertext_hex", "type": "textarea",
             "label": "Ciphertext (hex, ciphertext+tag)",
             "placeholder": "hex ciphertext (incl. 16-byte tag)",
             "required": False},
            {"name": "key_hex", "type": "text", "label": "Key (64 hex digits)",
             "placeholder": "000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F",
             "required": True},
            {"name": "nonce_hex", "type": "text", "label": "Nonce (24 hex digits)",
             "placeholder": "000000000000000000000000", "required": True},
            {"name": "aad", "type": "textarea", "label": "AAD (optional, authenticated)",
             "placeholder": "optional authenticated data", "default": "",
             "required": False},
        ]),
        "result_type": "object",
        "security_status": "secure",
        "reversible": True,
        "key_kind": "256-bit key (hex) + 96-bit nonce",
        "block_size": "stream cipher + Poly1305 tag",
        "description": "Authenticated encryption from RFC 8439 (TLS 1.3): "
                       "ChaCha20 stream cipher plus a Poly1305 MAC tag.",
        "formula": "C = ChaCha20(P); τ = Poly1305(key, A, C)",
    },
    "hmac": {
        "module": hmac_alg,
        "name": "HMAC",
        "category": "mac",
        "operations": ["sign", "verify"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Important message", "required": True},
            {"name": "key", "type": "text", "label": "Secret key",
             "placeholder": "super-secret-key", "required": True},
            {"name": "algorithm", "type": "select", "label": "Hash algorithm",
             "options": ["sha256", "sha512"], "default": "sha256",
             "required": True},
            {"name": "output_format", "type": "select", "label": "MAC encoding",
             "options": ["hex", "base64"], "default": "hex", "required": True},
            {"name": "mac", "type": "text", "label": "Provided MAC (for verify)",
             "placeholder": "hex/base64 MAC to check", "required": False},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "shared secret key",
        "block_size": "RIPEMD/64-byte input blocks",
        "description": "Keyed-Hash Message Authentication Code: a keyed hash "
                       "that proves message integrity and authenticity.",
        "formula": "HMAC = H((K′ ⊕ opad) ‖ H((K′ ⊕ ipad) ‖ m))",
    },
    "pbkdf2": {
        "module": pbkdf2,
        "name": "PBKDF2",
        "category": "kdf",
        "operations": ["derive", "verify"],
        "fields": _fields([
            {"name": "password", "type": "text", "label": "Password",
             "placeholder": "correct horse battery staple", "required": True},
            {"name": "salt", "type": "text", "label": "Salt (text; blank = random)",
             "placeholder": "optional known salt", "default": "", "required": False},
            {"name": "salt_hex", "type": "text", "label": "Salt (hex, for verify)",
             "placeholder": "previous salt in hex", "required": False},
            {"name": "expected_key_hex", "type": "text",
             "label": "Expected derived key (hex, for verify)",
             "placeholder": "previously derived key", "required": False},
            {"name": "iterations", "type": "number", "label": "Iterations",
             "default": 100000, "required": True, "min": 1, "max": 10000000},
            {"name": "key_length", "type": "number", "label": "Derived key length (bytes)",
             "default": 32, "required": True, "min": 1, "max": 64},
            {"name": "algorithm", "type": "select", "label": "Hash algorithm",
             "options": ["sha256", "sha512"], "default": "sha256",
             "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "password + salt + iteration count",
        "block_size": "—",
        "description": "Key derivation / password hashing by iterating a PRF "
                       "(HMAC) over the password and salt (RFC 8018).",
        "formula": "F(P, S, c) = U₁ ⊕ U₂ ⊕ … ⊕ Uc",
    },
    "bcrypt": {
        "module": bcrypt_alg,
        "name": "bcrypt",
        "category": "kdf",
        "operations": ["hash_password", "verify"],
        "fields": _fields([
            {"name": "password", "type": "text", "label": "Password",
             "placeholder": "correct horse battery staple", "required": True},
            {"name": "rounds", "type": "number", "label": "Cost factor (rounds)",
             "default": 12, "required": False, "min": 4, "max": 31},
            {"name": "hash_str", "type": "text", "label": "bcrypt hash (for verify)",
             "placeholder": "$2b$12$… (from a previous hash_password)",
             "required": False},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "password + salt (self-contained in $2b$ hash)",
        "block_size": "—",
        "description": "Adaptive password-hashing built on the Blowfish key "
                       "schedule. The cost factor doubles the work each step.",
        "formula": "Blowfish key schedule over password+128-bit salt",
    },
    "scrypt": {
        "module": scrypt_alg,
        "name": "scrypt",
        "category": "kdf",
        "operations": ["derive", "verify"],
        "fields": _fields([
            {"name": "password", "type": "text", "label": "Password",
             "placeholder": "correct horse battery staple", "required": True},
            {"name": "salt", "type": "text", "label": "Salt (text; blank = random)",
             "placeholder": "optional known salt", "default": "", "required": False},
            {"name": "salt_hex", "type": "text", "label": "Salt (hex, for verify)",
             "placeholder": "previous salt in hex", "required": False},
            {"name": "expected_key_hex", "type": "text",
             "label": "Expected derived key (hex, for verify)",
             "placeholder": "previously derived key", "required": False},
            {"name": "n", "type": "number", "label": "Cost parameter N (power of 2)",
             "default": 16384, "required": True, "min": 2, "max": 1048576},
            {"name": "r", "type": "number", "label": "Block size r",
             "default": 8, "required": True, "min": 1, "max": 64},
            {"name": "p", "type": "number", "label": "Parallelism p",
             "default": 1, "required": True, "min": 1, "max": 16},
            {"name": "key_length", "type": "number", "label": "Derived key length (bytes)",
             "default": 32, "required": True, "min": 1, "max": 128},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "password + salt + (N, r, p)",
        "block_size": "—",
        "description": "Memory-hard key derivation (RFC 7914): PBKDF2 + the "
                       "Salsa20/8 core, resistant to GPU/ASIC brute force.",
        "formula": "PBKDF2 then ROMix (Salsa20/8 inner loop)",
    },
    "argon2": {
        "module": argon2_alg,
        "name": "Argon2",
        "category": "kdf",
        "operations": ["hash_password", "verify"],
        "fields": _fields([
            {"name": "password", "type": "text", "label": "Password",
             "placeholder": "correct horse battery staple", "required": True},
            {"name": "time_cost", "type": "number", "label": "Time cost t (optional)",
             "default": 3, "required": False, "min": 1, "max": 10},
            {"name": "memory_cost", "type": "number",
             "label": "Memory cost m Kib (optional)", "default": 65536,
             "required": False, "min": 8, "max": 1048576},
            {"name": "parallelism", "type": "number", "label": "Parallelism p (optional)",
             "default": 2, "required": False, "min": 1, "max": 16},
            {"name": "hash_length", "type": "number", "label": "Hash length bytes (optional)",
             "default": 32, "required": False, "min": 1, "max": 64},
            {"name": "variant", "type": "select", "label": "Variant",
             "options": ["argon2id", "argon2i", "argon2d"], "default": "argon2id",
             "required": False},
            {"name": "hash_str", "type": "text", "label": "Argon2 hash (for verify)",
             "placeholder": "$argon2id$v=19$m=65536,t=3,p=2$…",
             "required": False},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "password + random salt (self-contained in hash)",
        "block_size": "—",
        "description": "Winner of the Password Hashing Competition (2015); "
                       "the current recommended password hasher (argon2id).",
        "formula": "B(0) ‖ H′; memory-hard BLAKE2b rounds over a 2D lane matrix",
    },
    "hkdf": {
        "module": hkdf,
        "name": "HKDF",
        "category": "kdf",
        "operations": ["derive"],
        "fields": _fields([
            {"name": "ikm", "type": "text", "label": "Input key material (ikm)",
             "placeholder": "shared secret or random seed", "required": True},
            {"name": "salt", "type": "text", "label": "Salt (text; blank = random)",
             "placeholder": "optional salt", "default": "", "required": False},
            {"name": "info", "type": "text",
             "label": "Context info (optional)",
             "placeholder": "application context, e.g. 'encryption-key'",
             "default": "", "required": False},
            {"name": "length", "type": "number", "label": "Output length (bytes)",
             "default": 32, "required": True, "min": 1, "max": 4096},
            {"name": "algorithm", "type": "select", "label": "Hash algorithm",
             "options": ["sha256", "sha512"], "default": "sha256",
             "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "ikm + optional salt/info",
        "block_size": "—",
        "description": "Key derivation function (RFC 5869): HKDF-Extract + "
                       "HKDF-Expand, turning one master key into many.",
        "formula": "PRK = HMAC(salt, ikm); OKM = HMAC(PRK, T‖info‖0x01)…",
    },
    "ecdh": {
        "module": ecdh,
        "name": "ECDH",
        "category": "key_exchange",
        "operations": ["exchange"],
        "fields": _fields([
            {"name": "curve", "type": "select", "label": "Curve",
             "options": ["p256", "p384", "p521"], "default": "p256",
             "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure_with_auth",
        "reversible": False,
        "key_kind": "EC key pair (private scalar + public point)",
        "block_size": "—",
        "description": "Elliptic-curve Diffie–Hellman: derive a shared secret "
                       "from two curve key pairs. Needs authentication.",
        "formula": "S = a·B = b·A (x-coordinate)",
    },
    "x25519": {
        "module": x25519,
        "name": "X25519",
        "category": "key_exchange",
        "operations": ["exchange"],
        "fields": _fields([]),
        "result_type": "text",
        "security_status": "secure_with_auth",
        "reversible": False,
        "key_kind": "32-byte private scalar + 32-byte public key",
        "block_size": "—",
        "description": "RFC 7748 Elliptic-curve Diffie–Hellman over Curve25519 "
                       "(x-coordinate only). Fast and constant-time.",
        "formula": "u = X25519(private, u-coordinate); s = X25519(a, B)",
    },
    "ecdsa": {
        "module": ecdsa_alg,
        "name": "ECDSA",
        "category": "signature",
        "operations": ["generate_keys", "sign", "verify"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Message to sign", "required": True},
            {"name": "curve", "type": "select", "label": "Curve",
             "options": ["p256", "p384", "p521"], "default": "p256",
             "required": True},
            {"name": "signature_hex", "type": "text", "label": "Signature (hex, for verify)",
             "placeholder": "DER signature from sign", "required": False},
            {"name": "public_hex", "type": "text",
             "label": "Public key (hex, for verify)",
             "placeholder": "uncompressed point from sign", "required": False},
            {"name": "public_x", "type": "number", "label": "Public key x (optional)",
             "required": False},
            {"name": "public_y", "type": "number", "label": "Public key y (optional)",
             "required": False},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "EC key pair (FIPS 186-4)",
        "block_size": "—",
        "description": "Elliptic-curve digital signatures (r, s). It "
                       "authenticates — it does not encrypt.",
        "formula": "r = (k·G).x mod n; s = k⁻¹(z + r·d) mod n",
    },
    "ed25519": {
        "module": ed25519_alg,
        "name": "Ed25519",
        "category": "signature",
        "operations": ["generate_keys", "sign", "verify"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Message to sign", "required": True},
            {"name": "signature_hex", "type": "text", "label": "Signature (hex, for verify)",
             "placeholder": "64-byte signature from sign", "required": False},
            {"name": "public_hex", "type": "text",
             "label": "Public key (hex, for verify)",
             "placeholder": "32-byte public key from sign", "required": False},
            {"name": "private_hex", "type": "text",
             "label": "Private key (hex, optional)",
             "placeholder": "blank = auto-generate", "required": False},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "32-byte key pair",
        "block_size": "—",
        "description": "Modern deterministic signatures (RFC 8032) on the "
                       "Edwards curve. Fast, constant-time, 64-byte signatures.",
        "formula": "R = r·B; S = r + SHA-512(R‖A‖M)·a (mod L)",
    },
    "rsa": {
        "module": rsa,
        "name": "RSA",
        "category": "asymmetric",
        "operations": ["encrypt", "decrypt", "generate_keys", "encrypt_oaep",
                       "decrypt_oaep", "sign_pss", "verify_pss"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "HI", "required": True},
            {"name": "p", "type": "number", "label": "Prime p", "default": 61,
             "required": True, "min": 2},
            {"name": "q", "type": "number", "label": "Prime q", "default": 53,
             "required": True, "min": 2},
            {"name": "e", "type": "number", "label": "Exponent e (optional)",
             "default": 65537, "required": False, "min": 3},
            {"name": "public_key_pem", "type": "textarea",
             "label": "Public key (PEM, optional)",
             "placeholder": "-----BEGIN PUBLIC KEY----- ... (blank = auto-generate)",
             "required": False},
            {"name": "private_key_pem", "type": "textarea",
             "label": "Private key (PEM, optional)",
             "placeholder": "-----BEGIN PRIVATE KEY----- ... (blank = auto-generate for OAEP/PSS)",
             "required": False},
            {"name": "ciphertext_hex", "type": "textarea",
             "label": "Ciphertext (hex, for OAEP decrypt)",
             "placeholder": "hex ciphertext to decrypt", "required": False},
            {"name": "signature_hex", "type": "text",
             "label": "Signature (hex, for PSS verify)",
             "placeholder": "hex signature to verify", "required": False},
        ]),
        "result_type": "number",
        "security_status": "secure_with_padding",
        "reversible": True,
        "key_kind": "primes p, q + exponent e",
        "block_size": "integer < n",
        "description": "Public-key cryptosystem based on the hardness of factoring.",
        "formula": "C = Mᵉ mod n; M = Cᵈ mod n",
    },
    "diffie_hellman": {
        "module": diffie_hellman,
        "name": "Diffie–Hellman",
        "category": "key_exchange",
        "operations": ["exchange"],
        "fields": _fields([
            {"name": "p", "type": "number", "label": "Prime p", "default": 23,
             "required": True, "min": 2},
            {"name": "g", "type": "number", "label": "Generator g", "default": 5,
             "required": True, "min": 2},
            {"name": "a_private", "type": "number", "label": "Alice private (a)",
             "default": 6, "required": True, "min": 1},
            {"name": "b_private", "type": "number", "label": "Bob private (b)",
             "default": 15, "required": True, "min": 1},
        ]),
        "result_type": "number",
        "security_status": "secure_with_auth",
        "reversible": False,
        "key_kind": "p, g and two private keys",
        "block_size": "—",
        "description": "Key exchange protocol — derives a shared secret over "
                       "an insecure channel.",
        "formula": "s = Bᵃ mod p = Aᵇ mod p",
    },
    "elgamal": {
        "module": elgamal,
        "name": "ElGamal",
        "category": "asymmetric",
        "operations": ["encrypt", "decrypt", "generate_keys"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message (for encrypt)",
             "placeholder": "HI", "required": True},
            {"name": "p", "type": "number", "label": "Prime p", "default": 467,
             "required": True, "min": 2},
            {"name": "g", "type": "number", "label": "Generator g", "default": 2,
             "required": True, "min": 2},
            {"name": "x", "type": "number", "label": "Private key x", "default": 127,
             "required": True, "min": 1},
            {"name": "c1", "type": "number", "label": "Cipher component c1 (decrypt)",
             "required": False, "min": 1},
            {"name": "c2", "type": "number", "label": "Cipher component c2 (decrypt)",
             "required": False, "min": 1},
        ]),
        "result_type": "object",
        "security_status": "secure_with_padding",
        "reversible": True,
        "key_kind": "p, g, private x, ephemeral k",
        "block_size": "integer < p",
        "description": "Randomized asymmetric encryption based on the DH problem.",
        "formula": "c1 = gᵏ mod p; c2 = m·yᵏ mod p",
    },
    "sha256": {
        "module": sha256,
        "name": "SHA-256",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "none",
        "block_size": "512-bit blocks",
        "description": "One-way cryptographic hash producing a 256-bit digest.",
        "formula": "compression function, 64 rounds",
    },
    "sha512": {
        "module": sha512,
        "name": "SHA-512",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "none",
        "block_size": "1024-bit blocks",
        "description": "One-way cryptographic hash producing a 512-bit digest.",
        "formula": "compression function, 80 rounds",
    },
    "sha1": {
        "module": sha1,
        "name": "SHA-1",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
        ]),
        "result_type": "text",
        "security_status": "broken_deprecated",
        "reversible": False,
        "key_kind": "none",
        "block_size": "512-bit blocks",
        "description": "Legacy one-way hash; SHA-1 collisions are practical and it is deprecated (160-bit digest).",
        "formula": "compression function, 80 rounds",
    },
    "md5": {
        "module": md5,
        "name": "MD5",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
        ]),
        "result_type": "text",
        "security_status": "broken",
        "reversible": False,
        "key_kind": "none",
        "block_size": "512-bit blocks",
        "description": "Legacy one-way hash with broken collision resistance (128-bit digest).",
        "formula": "compression function, 4 rounds × 16 steps",
    },
    "sha3": {
        "module": sha3,
        "name": "SHA-3",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
            {"name": "variant", "type": "select", "label": "Variant",
             "options": ["224", "256", "384", "512"], "default": "256",
             "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "none",
        "block_size": "Keccak sponge (rate 144/136/104/72 bytes)",
        "description": "Sponge-based one-way hash (Keccak-f[1600], SHA-3-224/256/384/512).",
        "formula": "Keccak-f[1600] sponge, 24 rounds",
    },
    "blake2": {
        "module": blake2,
        "name": "BLAKE2",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
            {"name": "variant", "type": "select", "label": "Variant",
             "options": ["512", "256"], "default": "512",
             "required": True},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "none",
        "block_size": "128-byte blocks (BLAKE2b) / 64-byte blocks (BLAKE2s)",
        "description": "Fast one-way hash with parameterized variants (BLAKE2b-512, BLAKE2s-256).",
        "formula": "BLAKE2b: 12 rounds; BLAKE2s: 10 rounds",
    },
    "blake3": {
        "module": blake3,
        "name": "BLAKE3",
        "category": "hashing",
        "operations": ["hash"],
        "fields": _fields([
            {"name": "message", "type": "textarea", "label": "Message",
             "placeholder": "Hello, cryptography!", "required": True},
            {"name": "length", "type": "number", "label": "Digest length (bytes)",
             "default": 32, "required": True, "min": 1, "max": 64},
        ]),
        "result_type": "text",
        "security_status": "secure",
        "reversible": False,
        "key_kind": "none",
        "block_size": "64-byte blocks / 1024-byte chunks",
        "description": "Very fast one-way hash built as a Merkle tree of chunks (extendable output).",
        "formula": "BLAKE2s rounds over a Merkle tree of chunks",
    },
}


def get_catalog() -> List[dict]:
    """List all algorithms with metadata for the frontend."""
    items = []
    for alg_id, info in ALGORITHMS.items():
        items.append({
            "id": alg_id,
            "name": info["name"],
            "category": info["category"],
            "category_label": CATEGORY_LABELS[info["category"]],
            "operations": info["operations"],
            "fields": info["fields"],
            "security_status": info["security_status"],
            "reversible": info["reversible"],
            "key_kind": info["key_kind"],
            "block_size": info["block_size"],
            "description": info["description"],
            "formula": info["formula"],
        })
    return items


def get_algorithm(alg_id: str) -> dict:
    if alg_id not in ALGORITHMS:
        raise KeyError(f"Unknown algorithm: {alg_id}")
    return ALGORITHMS[alg_id]


def get_module(alg_id: str):
    return get_algorithm(alg_id)["module"]


def categories_summary() -> dict:
    summary = {
        "total": len(ALGORITHMS),
        "classical": 0,
        "symmetric": 0,
        "asymmetric": 0,
        "key_exchange": 0,
        "hashing": 0,
        "mac": 0,
        "kdf": 0,
        "aead": 0,
        "signature": 0,
    }
    for info in ALGORITHMS.values():
        summary.setdefault(info["category"], 0)
        summary[info["category"]] += 1
    return summary