"""HybridEncryptionService - RSA-OAEP key wrapping + AEAD data encryption.

Design (deliberately standard, no custom protocol):

::

    file bytes ──▶ AES-256-GCM (or ChaCha20-Poly1305) ──▶ ciphertext
                        ▲
    random 32-byte key ─┘
    random key ──▶ RSA-OAEP (MGF1 + SHA-256) ──▶ wrapped key (RSA can wrap
                                                   only the small random key,
                                                   never the file itself)

The symmetric key and nonce are always generated by the OS CSPRNG. The
wrapped key, nonce, tag and metadata are stored in the versioned container so
the artifact is self-describing.
"""

from __future__ import annotations

import base64
import os
from pathlib import PurePosixPath
from typing import Any, Dict

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

from backend.app.lab import aead, container
from backend.app.lab.errors import LabCryptoError, LabValidationError

SYMMETRIC_ALGORITHMS = aead.ALGORITHMS
OAEP_HASHES = {
    "sha256": hashes.SHA256,
    "sha384": hashes.SHA384,
    "sha512": hashes.SHA512,
}


def _b64e(raw: bytes) -> str:
    return base64.b64encode(raw).decode("ascii")


def _b64d(value: str, field: str) -> bytes:
    try:
        return base64.b64decode(value.encode("ascii"), validate=True)
    except (ValueError, UnicodeEncodeError) as exc:
        raise LabCryptoError(f"Malformed container field: {field}.") from exc


def _oaep(name: str):
    if name not in OAEP_HASHES:
        raise LabValidationError("OAEP hash must be sha256, sha384 or sha512.")
    return padding.OAEP(mgf=padding.MGF1(OAEP_HASHES[name]()), algorithm=OAEP_HASHES[name](), label=None)


def _load_public(pem: str):
    if not isinstance(pem, str) or "PUBLIC KEY" not in pem:
        raise LabValidationError("A PEM-encoded RSA public key is required.")
    try:
        key = serialization.load_pem_public_key(pem.encode("utf-8"))
    except Exception as exc:  # noqa: BLE001 - normalize library errors
        raise LabValidationError("Could not load the RSA public key.") from exc
    if not isinstance(key, rsa.RSAPublicKey):
        raise LabValidationError("Hybrid encryption requires an RSA public key.")
    return key


def _load_private(pem: str):
    if not isinstance(pem, str) or "PRIVATE KEY" not in pem:
        raise LabValidationError("A PEM-encoded RSA private key is required.")
    try:
        key = serialization.load_pem_private_key(pem.encode("utf-8"), password=None)
    except Exception as exc:  # noqa: BLE001 - normalize library errors
        raise LabValidationError("Could not load the RSA private key.") from exc
    if not isinstance(key, rsa.RSAPrivateKey):
        raise LabValidationError("Hybrid decryption requires an RSA private key.")
    return key


class HybridEncryptionService:
    """Encrypt arbitrary bytes under RSA-OAEP-wrapped AEAD keys."""

    algorithms = SYMMETRIC_ALGORITHMS

    @staticmethod
    def encrypt(
        data: bytes,
        rsa_public_key_pem: str,
        *,
        symmetric_algorithm: str = "aes_gcm",
        hash_algorithm: str = "sha256",
        filename: str = "",
        mime_type: str = "",
    ) -> bytes:
        if not isinstance(data, (bytes, bytearray)):
            raise LabValidationError("Input data must be bytes (binary-safe).")
        if symmetric_algorithm not in aead.ALGORITHMS:
            raise LabValidationError(
                "Unsupported symmetric algorithm. Allowed: aes_gcm, chacha20_poly1305."
            )
        public = _load_public(rsa_public_key_pem)
        payload = bytes(data)

        key = os.urandom(aead.KEY_BYTES)
        nonce = os.urandom(aead.NONCE_BYTES)
        ciphertext, tag = aead.encrypt(symmetric_algorithm, key, nonce, payload)

        try:
            wrapped_key = public.encrypt(key, _oaep(hash_algorithm))
        except ValueError as exc:
            raise LabValidationError(
                "RSA key is too small to wrap the symmetric key with OAEP."
            ) from exc

        name = filename or ""
        extension = PurePosixPath(name.replace("\\", "/")).suffix.lower()
        header = container.new_header(
            mode="hybrid",
            algorithm=symmetric_algorithm,
            kdf=None,
            kdf_params={"oaep_hash": hash_algorithm},
            salt_b64=None,
            nonce_b64=_b64e(nonce),
            tag_b64=_b64e(tag),
            wrapped_key_b64=_b64e(wrapped_key),
            key_algorithm="rsa",
            key_size=public.key_size,
            original_filename=name,
            original_extension=extension,
            original_mime_type=mime_type or "",
            original_size=len(payload),
        )
        return container.serialize(header, ciphertext)

    @staticmethod
    def decrypt(package: bytes, rsa_private_key_pem: str) -> Dict[str, Any]:
        header, ciphertext = container.parse(package)
        if header["mode"] != "hybrid":
            raise LabCryptoError("Container is not a hybrid-encryption artifact.")
        if not header.get("wrapped_key_b64"):
            raise LabCryptoError("Container is missing the wrapped symmetric key.")
        private = _load_private(rsa_private_key_pem)
        hash_name = (header.get("kdf_params") or {}).get("oaep_hash", "sha256")

        try:
            key = private.decrypt(
                _b64d(header["wrapped_key_b64"], "wrapped_key_b64"), _oaep(hash_name)
            )
        except LabValidationError:
            raise
        except Exception as exc:  # noqa: BLE001 - OAEP integrity failure or wrong key
            raise LabCryptoError(
                "Could not unwrap the symmetric key: wrong private key or tampered file."
            ) from exc

        nonce = _b64d(header["nonce_b64"], "nonce_b64")
        tag = _b64d(header["tag_b64"], "tag_b64")
        data = aead.decrypt(header["algorithm"], key, nonce, tag, ciphertext)
        if len(data) != header["original_size"]:
            raise LabCryptoError("Decrypted size does not match the container metadata.")
        return {"data": data, "header": header}
